name: Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tags:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step for main branch
        id: tag
        if: github.ref == 'refs/heads/main'
        run: echo "::set-output name=new_version::${{ steps.tag_version.outputs.new_version }}"
      - name: Add tag to output step for pull request
        id: tag
        if: github.ref !== 'refs/heads/main'
        run: echo "::set-output name=new_version::pr-${{ github.event.number }}"

  ubi8_image:
    needs: tags
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/build-ubi8"
      image_version: ${{ needs.tags.outputs.new_version }}  
      image_build_args: "baseImage=registry.access.redhat.com/ubi8/ubi:latest"
      image_context: ./ubi
      image_file: "./Dockerfile.ubi8"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  python38_image:
    needs: [tags,ubi8_image]
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/build-ubi8-python3.8"
      image_version: ${{ needs.tags.outputs.new_version }}  
      image_build_args: "baseImage=axaguildev/build-ubi8:${{ needs.tags.outputs.new_version }}"
      image_context: ./build/Python38
      image_file: "./build/Python38/Dockerfile.ubi8"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  python310_image:
    needs: [tags,ubi8_image]
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/build-ubi8-python3.10"
      image_version: ${{ needs.tags.outputs.new_version }}  
      image_build_args: "baseImage=axaguildev/build-ubi8:${{ needs.tags.outputs.new_version }}"
      image_context: ./build/Python310
      image_file: "./build/Python310/Dockerfile.ubi8"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  python38_tesseract_image:
    needs: [tags,ubi8_image,python38_image]
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/build-ubi8-python3.8-tesseract"
      image_version: ${{ needs.tags.outputs.new_version }}  
      image_build_args: "baseImage=axaguildev/build-ubi8-python3.8:${{ needs.tags.outputs.new_version }}"
      image_context: ./build/Python310
      image_file: "./build/Python310/Dockerfile.ubi8"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}