name: Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tags:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step
        id: tag
        if: github.ref == 'refs/heads/main'
        run: echo "::set-output name=new_version::${{ steps.tag_version.outputs.new_version }}"

  build_ubi8_image:
    needs: tags
    environment: MLOpsPython
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/build-ubi8"
      image_version: ${{ needs.tags.outputs.new_version }}  
      image_build_args: "baseImage=registry.access.redhat.com/ubi8/ubi:latest"
      image_context: ./ubi
      image_file: "./Dockerfile.ubi8"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #build_ubi8_image:
  #  environment: MLOpsPython
  #  
  #  runs-on: ubuntu-latest
  #  
  #  steps:   
  #  - uses: actions/checkout@v3
  #    with:
  #      fetch-depth: 0
#
  #  - name: Log in to Docker Hub
  #    uses: docker/login-action@v2
  #    with:
  #      username: ${{ secrets.DOCKER_USERNAME }}
  #      password: ${{ secrets.DOCKER_PASSWORD }}
#
  #  - name: Extract metadata (tags, labels) for Docker
  #    id: meta
  #    uses: docker/metadata-action@v2
  #    with:
  #      images: axaguildev/build-ubi8
#
  #  - name: Build and push Docker image
  #    if: github.ref == 'refs/heads/main'
  #    uses: docker/build-push-action@v3
  #    with:
  #      context: ./ubi
  #      file : "./Dockerfile.ubi8"
  #      
  #      push: true
  #      tags: axaguildev/build-ubi8:${{ needs.tags.outputs.new_version }},axaguildev/build-ubi8:latest
  #      labels: ${{ steps.meta.outputs.labels }}
#
  #  - name: Build and push Docker image
  #    if: github.ref != 'refs/heads/main'
  #    uses: docker/build-push-action@v3
  #    with:
  #      context: ./ubi
  #      file : "./Dockerfile.ubi8"
  #      build-args: "baseImage=registry.access.redhat.com/ubi8/ubi:latest"
  #      push: true
  #      tags: axaguildev/build-ubi8:pr-${{ github.event.number }}
  #      labels: ${{ steps.meta.outputs.labels }}

  build_python38_image:
    environment: MLOpsPython
    needs: [tags,build_ubi8_image]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: axaguildev/build-ubi8-python3.8

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./build/Python38
        file : "./build/Python38/Dockerfile.ubi8"
        build-args: "baseImage=axaguildev/build-ubi8:${{ needs.tags.outputs.new_version }}"
        push: true
        tags: axaguildev/build-ubi8-python3.8:${{ needs.tags.outputs.new_version }},axaguildev/build-ubi8-python3.8:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./build/Python38
        file : "./build/Python38/Dockerfile.ubi8"
        build-args: "baseImage=axaguildev/build-ubi8:pr-${{ github.event.number }}"
        push: true
        tags: axaguildev/build-ubi8-python3.8:pr-${{ github.event.number }}
        labels: ${{ steps.meta.outputs.labels }}

  build_python310_image:
    environment: MLOpsPython
    needs: [tags,build_ubi8_image]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: axaguildev/build-ubi8-python3.10

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./build/Python310
        file : "./build/Python310/Dockerfile.ubi8"
        build-args: "baseImage=axaguildev/build-ubi8:${{ needs.tags.outputs.new_version }}"
        push: true
        tags: axaguildev/build-ubi8-python3.10:${{ needs.tags.outputs.new_version }},axaguildev/build-ubi8-python3.10:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./build/Python310
        file : "./build/Python310/Dockerfile.ubi8"
        build-args: "baseImage=axaguildev/build-ubi8:pr-${{ github.event.number }}"
        push: true
        tags: axaguildev/build-ubi8-python3.10:pr-${{ github.event.number }}
        labels: ${{ steps.meta.outputs.labels }}
        
  build_python38_tesseract_image:
    environment: MLOpsPython
    needs: [tags,build_python38_image]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: axaguildev/build-ubi8-python3.8-tesseract

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./ubi
        file : "./Dockerfile.ubi8-tesseract"
        build-args: "baseImage=axaguildev/build-ubi8-python3.8:${{ needs.tags.outputs.new_version }}"
        push: true
        tags: axaguildev/build-ubi8-python3.8-tesseract:${{ needs.tags.outputs.new_version }},axaguildev/build-ubi8-python3.8-tesseract:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ./ubi
        file : "./Dockerfile.ubi8-tesseract"
        build-args: "baseImage=axaguildev/build-ubi8-python3.8:pr-${{ github.event.number }}"
        push: true
        tags: axaguildev/build-ubi8-python3.8-tesseract:pr-${{ github.event.number }}
        labels: ${{ steps.meta.outputs.labels }}
