name: Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tags:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        #if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step for main branch
        id: tag_main
        #if: github.ref == 'refs/heads/main'
        run: echo "new_version=${{ steps.tag_version.outputs.new_version }}" >> $GITHUB_OUTPUT
      #- name: Add tag to output step for pull request
      #  id: tag_pr
      #  if: github.ref != 'refs/heads/main'
      #  run:  echo "new_version=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT

  calver:
    needs: tags
    name: Create CalVer tag
    steps:
      - name: Echo
        run: |
          echo ${{ needs.tags.outputs.new_version }}

#  build_ubi8_image:
#    needs: tags
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/build-ubi8"
#      image_version: pr-${{ github.event.number }}
#      image_build_args: "baseImage=registry.access.redhat.com/ubi8/ubi:latest"
#      image_context: ./ubi
#      image_file: "./Dockerfile.ubi8"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#  runtime_ubi8_image:
#    needs: tags
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/runtime-ubi8"
#      image_version: ${{ needs.tags.outputs.new_version }}
#      image_build_args: "baseImage=registry.access.redhat.com/ubi8/ubi-minimal:latest"
#      image_context: ./ubi
#      image_file: "./Dockerfile.ubi8-minimal"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#  build_python38_image:
#    needs: [tags,build_ubi8_image]
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/build-ubi8-python3.8"
#      image_version: pr-${{ github.event.number }} 
#      image_build_args: "baseImage=axaguildev/build-ubi8:pr-${{ github.event.number }}"
#      image_context: ./build/Python38
#      image_file: "./build/Python38/Dockerfile.ubi8"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#  runtime_python38_image:
#    needs: [tags,runtime_ubi8_image]
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/runtime-ubi8-python3.8"
#      image_version: pr-${{ github.event.number }} 
#      image_build_args: "baseImage=axaguildev/runtime-ubi8:pr-${{ github.event.number }}"
#      image_context: ./runtime/Python38
#      image_file: "./runtime/Python38/Dockerfile.ubi8"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#  build_python310_image:
#    needs: [tags,build_ubi8_image]
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/build-ubi8-python3.10"
#      image_version: pr-${{ github.event.number }} 
#      image_build_args: "baseImage=axaguildev/build-ubi8:pr-${{ github.event.number }} "
#      image_context: ./build/Python310
#      image_file: "./build/Python310/Dockerfile.ubi8"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#  runtime_python310_image:
#    needs: [tags,runtime_ubi8_image]
#    uses: ./.github/workflows/Docker.yml
#    with:
#      image_name: "axaguildev/runtime-ubi8-python3.10"
#      image_version: pr-${{ github.event.number }} 
#      image_build_args: "baseImage=axaguildev/runtime-ubi8:pr-${{ github.event.number }} "
#      image_context: ./runtime/Python310
#      image_file: "./runtime/Python310/Dockerfile.ubi8"
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  #build_python38_tesseract_image:
  #  needs: [tags,build_ubi8_image,build_python38_image]
  #  uses: ./.github/workflows/Docker.yml
  #  with:
  #    image_name: "axaguildev/build-ubi8-python3.8-tesseract"
  #    image_version: pr-${{ github.event.number }} 
  #    image_build_args: "baseImage=axaguildev/build-ubi8-python3.8:pr-${{ github.event.number }} 
  #    image_context: ./build/Python310
  #    image_file: "./build/Python310/Dockerfile.ubi8"
  #  secrets:
  #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}